
export const dates = [
{number:0, imgUrl:"https://picsum.photos/200", name:"Go for a long walk", moreInfo:""},
{number:1, imgUrl:"https://picsum.photos/200", name:"Picnic at the park", moreInfo:""},
{number:2, imgUrl:"https://picsum.photos/200", name:"Nature hike", moreInfo:""},
{number:3, imgUrl:"https://picsum.photos/200", name:"Cheese and wine evening", moreInfo:""},
{number:4, imgUrl:"https://picsum.photos/200", name:"Bungee jumping", moreInfo:""},
{number:5, imgUrl:"https://picsum.photos/200", name:"Ski trip", moreInfo:""},
{number:6, imgUrl:"https://picsum.photos/200", name:"Movie and pizza at home", moreInfo:""},
{number:7, imgUrl:"https://picsum.photos/200", name:"Go out to watch a Movie", moreInfo:""},
{number:8, imgUrl:"https://picsum.photos/200", name:"Concert", moreInfo:""},
{number:9, imgUrl:"https://picsum.photos/200", name:"Double date with another couple", moreInfo:""},
{number:10, imgUrl:"https://picsum.photos/200", name:"Get a massage", moreInfo:""},
{number:11, imgUrl:"https://picsum.photos/200", name:"Go out to eat at a fastfood restaurant", moreInfo:""},
{number:12, imgUrl:"https://picsum.photos/200", name:"Go out to eat at a fancy restaurant", moreInfo:""},
{number:13, imgUrl:"https://picsum.photos/200", name:"Cook a meal at home together", moreInfo:""},
{number:14, imgUrl:"https://picsum.photos/200", name:"Go to a lecture of interest", moreInfo:""},
{number:15, imgUrl:"https://picsum.photos/200", name:"Go to a Museam", moreInfo:""},
{number:16, imgUrl:"https://picsum.photos/200", name:"Go biking", moreInfo:""},
{number:17, imgUrl:"https://picsum.photos/200", name:"Board game night", moreInfo:""},
{number:18, imgUrl:"https://picsum.photos/200", name:"Go rollerblading", moreInfo:""},
{number:19, imgUrl:"https://picsum.photos/200", name:"Iceskating", moreInfo:""},
{number:20, imgUrl:"https://picsum.photos/200", name:"Bowling", moreInfo:""},
{number:21, imgUrl:"https://picsum.photos/200", name:"Billiards", moreInfo:""},
{number:22, imgUrl:"https://picsum.photos/200", name:"Stargazing", moreInfo:""},
{number:23, imgUrl:"https://picsum.photos/200", name:"Icecream", moreInfo:""},
{number:24, imgUrl:"https://picsum.photos/200", name:"Make shushi", moreInfo:""},
{number:25, imgUrl:"https://picsum.photos/200", name:"Go to library and choose books", moreInfo:""},
{number:26, imgUrl:"https://picsum.photos/200", name:"Night kumzitz", moreInfo:""},
{number:27, imgUrl:"https://picsum.photos/200", name:"Karaoke", moreInfo:""},
{number:28, imgUrl:"https://picsum.photos/200", name:"Art lesson", moreInfo:""},
{number:29, imgUrl:"https://picsum.photos/200", name:"Go see a play at the theatre", moreInfo:""},
{number:30, imgUrl:"https://picsum.photos/200", name:"Skydiving", moreInfo:""},
{number:31, imgUrl:"https://picsum.photos/200", name:"Scenic flight", moreInfo:""},
{number:32, imgUrl:"https://picsum.photos/200", name:"Fishing", moreInfo:""},
{number:33, imgUrl:"https://picsum.photos/200", name:"Clothes shopping", moreInfo:""},
{number:34, imgUrl:"https://picsum.photos/200", name:"volunteering at a local organization", moreInfo:""},
{number:35, imgUrl:"https://picsum.photos/200", name:"See a standup comedy show", moreInfo:""},
{number:36, imgUrl:"https://picsum.photos/200", name:"Boardwalk stroll", moreInfo:""},
{number:37, imgUrl:"https://picsum.photos/200", name:"Eating out at a new resteraunt", moreInfo:""},
{number:38, imgUrl:"https://picsum.photos/200", name:"Binge watch a series", moreInfo:""},
{number:39, imgUrl:"https://picsum.photos/200", name:"Buy tickets to a sporting event", moreInfo:""},
{number:40, imgUrl:"https://picsum.photos/200", name:"Gambling", moreInfo:""},
{number:41, imgUrl:"https://picsum.photos/200", name:"Boat ride", moreInfo:""},
{number:42, imgUrl:"https://picsum.photos/200", name:"Amusement park", moreInfo:""},
{number:43, imgUrl:"https://picsum.photos/200", name:"Water park", moreInfo:""},
{number:44, imgUrl:"https://picsum.photos/200", name:"Donate blood together", moreInfo:""},
{number:45, imgUrl:"https://picsum.photos/200", name:"Zoo", moreInfo:""},
{number:46, imgUrl:"https://picsum.photos/200", name:"Hot air balloon ride", moreInfo:""},
{number:47, imgUrl:"https://picsum.photos/200", name:"Rock repelling", moreInfo:""},
{number:48, imgUrl:"https://picsum.photos/200", name:"Art gallery visit", moreInfo:""},
{number:49, imgUrl:"https://picsum.photos/200", name:"Jeep tour", moreInfo:""}, 
]