const dates = [
{number:0, imgUrl:"./example", name:"Go for a long walk", moreInfo:""},
{number:1, imgUrl:"./example", name:"Picnic at the park", moreInfo:""},
{number:2, imgUrl:"./example", name:"Nature hike", moreInfo:""},
{number:3, imgUrl:"./example", name:"Cheese and wine evening", moreInfo:""},
{number:4, imgUrl:"./example", name:"Bungee jumping", moreInfo:""},
{number:5, imgUrl:"./example", name:"Ski trip", moreInfo:""},
{number:6, imgUrl:"./example", name:"Movie and pizza at home", moreInfo:""},
{number:7, imgUrl:"./example", name:"Go out to watch a Movie", moreInfo:""},
{number:8, imgUrl:"./example", name:"Concert", moreInfo:""},
{number:9, imgUrl:"./example", name:"Double date with another couple", moreInfo:""},
{number:10, imgUrl:"./example", name:"Get a massage", moreInfo:""},
{number:11, imgUrl:"./example", name:"Go out to eat at a fastfood restaurant", moreInfo:""},
{number:12, imgUrl:"./example", name:"Go out to eat at a fancy restaurant", moreInfo:""},
{number:13, imgUrl:"./example", name:"Cook a meal at home together", moreInfo:""},
{number:14, imgUrl:"./example", name:"Go to a lecture of interest", moreInfo:""},
{number:15, imgUrl:"./example", name:"Go to a Museam", moreInfo:""},
{number:16, imgUrl:"./example", name:"Go biking", moreInfo:""},
{number:17, imgUrl:"./example", name:"Board game night", moreInfo:""},
{number:18, imgUrl:"./example", name:"Go rollerblading", moreInfo:""},
{number:19, imgUrl:"./example", name:"Iceskating", moreInfo:""},
{number:20, imgUrl:"./example", name:"Bowling", moreInfo:""},
{number:21, imgUrl:"./example", name:"Billiards", moreInfo:""},
{number:22, imgUrl:"./example", name:"Stargazing", moreInfo:""},
{number:23, imgUrl:"./example", name:"Icecream", moreInfo:""},
{number:24, imgUrl:"./example", name:"Make shushi", moreInfo:""},
{number:25, imgUrl:"./example", name:"Go to library and choose books", moreInfo:""},
{number:26, imgUrl:"./example", name:"Night kumzitz", moreInfo:""},
{number:27, imgUrl:"./example", name:"Karaoke", moreInfo:""},
{number:28, imgUrl:"./example", name:"Art lesson", moreInfo:""},
{number:29, imgUrl:"./example", name:"Go see a play at the theatre", moreInfo:""},
{number:30, imgUrl:"./example", name:"Skydiving", moreInfo:""},
{number:31, imgUrl:"./example", name:"Scenic flight", moreInfo:""},
{number:32, imgUrl:"./example", name:"Fishing", moreInfo:""},
{number:33, imgUrl:"./example", name:"Clothes shopping", moreInfo:""},
{number:34, imgUrl:"./example", name:"volunteering at a local organization", moreInfo:""},
{number:35, imgUrl:"./example", name:"See a standup comedy show", moreInfo:""},
{number:36, imgUrl:"./example", name:"Boardwalk stroll", moreInfo:""},
{number:37, imgUrl:"./example", name:"Eating out at a new resteraunt", moreInfo:""},
{number:38, imgUrl:"./example", name:"Binge watch a series", moreInfo:""},
{number:39, imgUrl:"./example", name:"Buy tickets to a sporting event", moreInfo:""},
{number:40, imgUrl:"./example", name:"Gambling", moreInfo:""},
{number:41, imgUrl:"./example", name:"Boat ride", moreInfo:""},
{number:42, imgUrl:"./example", name:"Amusement park", moreInfo:""},
{number:43, imgUrl:"./example", name:"Water park", moreInfo:""},
{number:44, imgUrl:"./example", name:"Donate blood together", moreInfo:""},
{number:45, imgUrl:"./example", name:"Zoo", moreInfo:""},
{number:46, imgUrl:"./example", name:"Hot air balloon ride", moreInfo:""},
{number:47, imgUrl:"./example", name:"Rock repelling", moreInfo:""},
{number:48, imgUrl:"./example", name:"Art gallery visit", moreInfo:""},
{number:49, imgUrl:"./example", name:"Jeep tour", moreInfo:""},
]