export { dates as default };
const dates = [
{number:0, imgUrl:"../images/lectur.jpg", name:"Go for a long walk", moreInfo:""},
{number:1, imgUrl:"../images/longwalk.jpg", name:"Picnic at the park", moreInfo:""},
{number:2, imgUrl:"../images/.jpg", name:"Nature hike", moreInfo:""},
{number:3, imgUrl:"../images/.jpg", name:"Cheese and wine evening", moreInfo:""},
{number:4, imgUrl:"../images/.jpg", name:"Bungee jumping", moreInfo:""},
{number:5, imgUrl:"../images/.jpg", name:"Ski trip", moreInfo:""},
{number:6, imgUrl:"../images/.jpg", name:"Movie and pizza at home", moreInfo:""},
{number:7, imgUrl:"../images/.jpg", name:"Go out to watch a Movie", moreInfo:""},
{number:8, imgUrl:"../images/.jpg", name:"Concert", moreInfo:""},
{number:9, imgUrl:"../images/.jpg", name:"Double date with another couple", moreInfo:""},
{number:10, imgUrl:"../images/.jpg", name:"Get a massage", moreInfo:""},
{number:11, imgUrl:"../images/.jpg", name:"Go out to eat at a fastfood restaurant", moreInfo:""},
{number:12, imgUrl:"../images/.jpg", name:"Go out to eat at a fancy restaurant", moreInfo:""},
{number:13, imgUrl:"../images/.jpg", name:"Cook a meal at home together", moreInfo:""},
{number:14, imgUrl:"../images/.jpg", name:"Go to a lecture of interest", moreInfo:""},
{number:15, imgUrl:"../images/.jpg", name:"Go to a Museam", moreInfo:""},
{number:16, imgUrl:"../images/.jpg", name:"Go biking", moreInfo:""},
{number:17, imgUrl:"../images/.jpg", name:"Board game night", moreInfo:""},
{number:18, imgUrl:"../images/.jpg", name:"Go rollerblading", moreInfo:""},
{number:19, imgUrl:"../images/.jpg", name:"Iceskating", moreInfo:""},
{number:20, imgUrl:"../images/.jpg", name:"Bowling", moreInfo:""},
{number:21, imgUrl:"../images/.jpg", name:"Billiards", moreInfo:""},
{number:22, imgUrl:"../images/.jpg", name:"Stargazing", moreInfo:""},
{number:23, imgUrl:"../images/.jpg", name:"Icecream", moreInfo:""},
{number:24, imgUrl:"../images/.jpg", name:"Make shushi", moreInfo:""},
{number:25, imgUrl:"../images/.jpg", name:"Go to library and choose books", moreInfo:""},
{number:26, imgUrl:"../images/.jpg", name:"Night kumzitz", moreInfo:""},
{number:27, imgUrl:"../images/.jpg", name:"Karaoke", moreInfo:""},
{number:28, imgUrl:"../images/.jpg", name:"Art lesson", moreInfo:""},
{number:29, imgUrl:"../images/.jpg", name:"Go see a play at the theatre", moreInfo:""},
{number:30, imgUrl:"../images/.jpg", name:"Skydiving", moreInfo:""},
{number:31, imgUrl:"../images/.jpg", name:"Scenic flight", moreInfo:""},
{number:32, imgUrl:"../images/.jpg", name:"Fishing", moreInfo:""},
{number:33, imgUrl:"../images/.jpg", name:"Clothes shopping", moreInfo:""},
{number:34, imgUrl:"../images/.jpg", name:"volunteering at a local organization", moreInfo:""},
{number:35, imgUrl:"../images/.jpg", name:"See a standup comedy show", moreInfo:""},
{number:36, imgUrl:"../images/.jpg", name:"Boardwalk stroll", moreInfo:""},
{number:37, imgUrl:"../images/.jpg", name:"Eating out at a new resteraunt", moreInfo:""},
{number:38, imgUrl:"../images/.jpg", name:"Binge watch a series", moreInfo:""},
{number:39, imgUrl:"../images/.jpg", name:"Buy tickets to a sporting event", moreInfo:""},
{number:40, imgUrl:"../images/.jpg", name:"Gambling", moreInfo:""},
{number:41, imgUrl:"../images/.jpg", name:"Boat ride", moreInfo:""},
{number:42, imgUrl:"../images/.jpg", name:"Amusement park", moreInfo:""},
{number:43, imgUrl:"../images/.jpg", name:"Water park", moreInfo:""},
{number:44, imgUrl:"../images/.jpg", name:"Donate blood together", moreInfo:""},
{number:45, imgUrl:"../images/.jpg", name:"Zoo", moreInfo:""},
{number:46, imgUrl:"../images/.jpg", name:"Hot air balloon ride", moreInfo:""},
{number:47, imgUrl:"../images/.jpg", name:"Rock repelling", moreInfo:""},
{number:48, imgUrl:"../images/.jpg", name:"Art gallery visit", moreInfo:""},
{number:49, imgUrl:"../images/.jpg", name:"Jeep tour", moreInfo:""}, 
]