export { dates as default };
const dates = [
{number:0, imgUrl:"../images/lectur.jpg", name:"Go for a long walk", moreInfo:""},
{number:1, imgUrl:"../images/longwalk.jpg", name:"Picnic at the park", moreInfo:""},
{number:2, imgUrl:"", name:"Nature hike", moreInfo:""},
{number:3, imgUrl:"", name:"Cheese and wine evening", moreInfo:""},
{number:4, imgUrl:"", name:"Bungee jumping", moreInfo:""},
{number:5, imgUrl:"", name:"Ski trip", moreInfo:""},
{number:6, imgUrl:"", name:"Movie and pizza at home", moreInfo:""},
{number:7, imgUrl:"", name:"Go out to watch a Movie", moreInfo:""},
{number:8, imgUrl:"", name:"Concert", moreInfo:""},
{number:9, imgUrl:"", name:"Double date with another couple", moreInfo:""},
{number:10, imgUrl:"", name:"Get a massage", moreInfo:""},
{number:11, imgUrl:"", name:"Go out to eat at a fastfood restaurant", moreInfo:""},
{number:12, imgUrl:"", name:"Go out to eat at a fancy restaurant", moreInfo:""},
{number:13, imgUrl:"", name:"Cook a meal at home together", moreInfo:""},
{number:14, imgUrl:"", name:"Go to a lecture of interest", moreInfo:""},
{number:15, imgUrl:"", name:"Go to a Museam", moreInfo:""},
{number:16, imgUrl:"", name:"Go biking", moreInfo:""},
{number:17, imgUrl:"", name:"Board game night", moreInfo:""},
{number:18, imgUrl:"", name:"Go rollerblading", moreInfo:""},
{number:19, imgUrl:"", name:"Iceskating", moreInfo:""},
{number:20, imgUrl:"", name:"Bowling", moreInfo:""},
{number:21, imgUrl:"", name:"Billiards", moreInfo:""},
{number:22, imgUrl:"", name:"Stargazing", moreInfo:""},
{number:23, imgUrl:"", name:"Icecream", moreInfo:""},
{number:24, imgUrl:"", name:"Make shushi", moreInfo:""},
{number:25, imgUrl:"", name:"Go to library and choose books", moreInfo:""},
{number:26, imgUrl:"", name:"Night kumzitz", moreInfo:""},
{number:27, imgUrl:"", name:"Karaoke", moreInfo:""},
{number:28, imgUrl:"", name:"Art lesson", moreInfo:""},
{number:29, imgUrl:"", name:"Go see a play at the theatre", moreInfo:""},
{number:30, imgUrl:"", name:"Skydiving", moreInfo:""},
{number:31, imgUrl:"", name:"Scenic flight", moreInfo:""},
{number:32, imgUrl:"", name:"Fishing", moreInfo:""},
{number:33, imgUrl:"", name:"Clothes shopping", moreInfo:""},
{number:34, imgUrl:"", name:"volunteering at a local organization", moreInfo:""},
{number:35, imgUrl:"", name:"See a standup comedy show", moreInfo:""},
{number:36, imgUrl:"", name:"Boardwalk stroll", moreInfo:""},
{number:37, imgUrl:"", name:"Eating out at a new resteraunt", moreInfo:""},
{number:38, imgUrl:"", name:"Binge watch a series", moreInfo:""},
{number:39, imgUrl:"", name:"Buy tickets to a sporting event", moreInfo:""},
{number:40, imgUrl:"", name:"Gambling", moreInfo:""},
{number:41, imgUrl:"", name:"Boat ride", moreInfo:""},
{number:42, imgUrl:"", name:"Amusement park", moreInfo:""},
{number:43, imgUrl:"", name:"Water park", moreInfo:""},
{number:44, imgUrl:"", name:"Donate blood together", moreInfo:""},
{number:45, imgUrl:"", name:"Zoo", moreInfo:""},
{number:46, imgUrl:"", name:"Hot air balloon ride", moreInfo:""},
{number:47, imgUrl:"", name:"Rock repelling", moreInfo:""},
{number:48, imgUrl:"", name:"Art gallery visit", moreInfo:""},
{number:49, imgUrl:"", name:"Jeep tour", moreInfo:""}, 
]